# Generated by Django 2.2.4 on 2022-04-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20220424_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='book',
        ),
    ]
